
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 27 21:43:23 CST 2016
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */


  public static final int IDENTIFIER = 98;

  public static final int RBRACE = 17;

  public static final int LBRACE = 16;



  public static final int ASSIGN = 18;

  public static final int PLUS = 60;
  public static final int MULT = 14;

  public static final int EOF = 0;

  public static final int MINUS = 61;

  public static final int error = 1;
  public static final int FUNCTION = 101;
  public static final int LOOP = 102;
  public static final int PRINT = 103;
  public static final int NUMBER = 104;

}

